services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - user_network
    volumes:
      - postgre_data:/var/lib/postgresql/data

  redis:
    image: 'redis:8.0.0-alpine'
    container_name: 'redis'
    ports:
      - '6379:6379'
    environment:
      REDIS_PORT: 6379
    networks:
      - user_network
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: 'user_service'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
    env_file:
      - .env
    networks:
      - user_network
    depends_on:
      - postgres
      - redis

networks:
  user_network:
    driver: bridge

volumes:
  postgre_data:
  redis_data: